(defun journal ()
  "create new journal file"
  (interactive)
  (let (buffer-name)
    ;; (setq buffer-name (cl-loop for num from 0
    ;;                            for name = (format-time-string "%Y-%m-%d")
    ;;                            while (get-buffer name)
    ;;                            finally return name))
    (setq journal-name (concat "~/Documents/journal/" (format-time-string "%Y-%m-%d")))
    (switch-to-buffer buffer-name)
    (find-file journal-name)
    (unless (file-exists-p journal-name)
      (insert "* Morning Questions\n")
      (insert "** What Am I Grateful for?\n")
      (insert "** What Would Make Today Great?\n")
      (insert "** What Am I Worried About?\n")
      (insert "** What Am I Thinking of?\n")
      (insert "* Evening Questions\n")
      (insert "** How Am I feeling?\n")
      (insert "** What's Something Good That Happened Today?\n")
      (insert "** What Did I Do Well?\n")
      (insert "** What Could I Have Done Better?\n")
      (insert "* Additional Thoughts\n"))
  (goto-char (point-max))))
